### ISSUE TITLE
Alcuni spunti veloci

### ISSUE THREAD

**Issue by dagoneye** [ondata/covid19italia#1]
Ciao, 
l'idea è ottima, ovviamente. Non è il caso di aggregare gli sforzi di chi lo sta facendo in maniera sparsa, così da fare meno fatica tutti assieme? Sono incappato [nel lavoro di Carlo Torniai](https://github.com/carlotorniai/COVID-19-Italy) e in [quello di Davide Magno](https://github.com/DavideMagno/ItalianCovidData)? 

Così si rafforza il messaggio!
Matteo

**Comment by aborruso** [comment]
Caro @dagoneye sono d'accordo.

Può essere utile sottolineare cosa c'è di diverso tra i progetti. Qui di diverso c'è:

- produciamo il dataset dei [dati provinciali](https://github.com/ondata/covid19italia/blob/master/publication/provinceArchivioISTAT.csv);
- archiviamo i [raw data PDF](https://github.com/ondata/covid19italia/tree/master/pdfArchive) pubblicati nel tempo;
- abbiamo attivato il refreshing dell'archiviazione delle pagine principali a tema su web archive (compresi i link contenuti in ognuna).

Questi ultimi due punti per poter avere sempre i dati grezzi e ripartire con un sistema più efficiente di processing.

Che consigli di fare?

**Comment by aborruso** [comment]
@dagoneye ho iniziato ad aggiungere una sezione nel README https://github.com/ondata/covid19italia#altri-progetti-a-tema

**Comment by dagoneye** [comment]
Direi che è un'ottima cosa integrare il readme. Tra l'altro, ho visto che Carlo Torniai è già arrivato qui. Se vedo altro di correlato, faccio PR per integrare.

**Comment by nickprock** [comment]
Ciao a tutti,
altri spunti:

1. sul README aggiungerei la sezione TO DO. Così se qualche volontario ha voglia di dare una mano sugli sviluppi futuri può occuparsene

2. proprio in prospettiva del punto 1 aggiungerei il codice di condotta, se no diventa una Babele

Buona serata.

Nico

**Comment by aborruso** [comment]
Caro @nickprock prima di tutto benvenuto, mi fa piacere incontrarti qui :)

Sul punto 1), non ho al momento nulla di "critico" da proporre. Mi viene in mente soltanto una mini dashboard e sarebbe molto carino sfruttare le gh-pages, così è tutto contenuto qui.

Sul 2), hai un modellino da cui prendere spunto?

Grazie

**Comment by nickprock** [comment]
Sul punto 2, per le poche volte che ho usato il codice di condotta o la netiquette di un repo (i miei non sono così visitati da richiederla) mi sono sempre affidato al prestampato di github (come per il .gitignore).
Qui ci sono alcune linee guida:

https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

Se vi và nella prossima settimana cerco di documentarmi meglio, faccio fork e provo a scriverla in italiano. Se non và bene al massimo mi rigettate la pull request :)
