### ISSUE TITLE
Integrazione dati precedenti al rilascio dei PDF

### ISSUE THREAD

**Issue by alessiodl** [ondata/covid19italia#10]
Anche se non sono completi di tutte le info, ho "scrapato" i dati regionali fin da quando erano pubblicati solo tramite l'RSS del DPC. 
Li trovi qui, se vuoi integrarli nel tuo riepilogo e riempire il buco spazio dal 24 Febbrario al 1 Marzo

https://github.com/alessiodl/COVID19Feed2Json/blob/master/storico/regioni.csv

**Comment by alessiodl** [comment]
Per ogni regione ho anche inserito le coordinate tramite una semplice funziona di geocodifica
https://github.com/alessiodl/COVID19Feed2Json/blob/master/geocodifica.py

**Comment by aborruso** [comment]
@alessiodl facci tu una proposta di merge, a partire da questo file https://github.com/ondata/covid19italia/blob/master/publication/riepilogoArchivio.csv

E poi così, vedo se ha impatto lato codice.

Grazie

**Comment by alessiodl** [comment]
Ho predisposto un google sheet

https://docs.google.com/spreadsheets/d/1ocxWiB5d6SNEapYG_XlJtxGT962SYsrqw4-dhyXPn-o/edit?usp=sharing

siccome prima del 28 uscivano due aggiornamenti giornalieri, ho aggiunto l'orario al datetime per uniformità, anche se per le date successive non serve

**Comment by aborruso** [comment]
@alessiodl ho aggiunto una colonna fonte.

Scrivi per i tuoi, l'URL che hai usato come fonte?

**Comment by alessiodl** [comment]
Fatto
