### ISSUE TITLE
Attivare archivazione periodica della  Matrice degli stati clinici Covid-19 in Lombardia

### ISSUE THREAD

**Issue by aborruso** [ondata/covid19italia#100]
https://hub.dati.lombardia.it/Sanit-/Matrice-degli-stati-clinici-Covid-19-inviati-a-ISS/7jw9-ygfv

**Comment by opencovid-mr** [comment]
Qui CSV raw con precedente aggiornamento (casi fino al 9 febbraio) nel caso servisse per lo storico:

https://raw.githubusercontent.com/opencovid-mr/Lombardia-Stati_Clinici/main/data/2021-02-16.csv

**Comment by aborruso** [comment]
Ciao @opencovid-mr direi che in questo caso, possiamo farne a meno.

Ho attivato download giornaliero e visto che siamo su git, il dato sarà aggiornato soltanto se ci sono modifiche e lo storico delle modifiche verrà archiviato e sottoposto a log

**Comment by aborruso** [comment]
@opencovid-mr  grazie per averci chiesto di attivare la cosa
