### ISSUE TITLE
Aggiornamento Agenas

### ISSUE THREAD

**Issue by Paulsword** [ondata/covid19italia#102]
Buonasera, ciao

mi chiedevo se ci fosse un problema con l'aggiornamento dei dati Agenas, che sono rimasti al 31/3

Grazie mille

**Comment by aborruso** [comment]
Ciao @Paulsword purtroppo c'è stato un "fallimento" dell'action programmata https://github.com/ondata/covid19italia/actions/runs/709908855

Quello di oggi avverrà a breve.

Grazie per la nota
