### ISSUE TITLE
Problema file "areeStorico"

### ISSUE THREAD

**Issue by jumpjack** [ondata/covid19italia#105]
Ma per i file "areeStorico" prendete i dati così come sono dal sito DPC, aggiungendo solo il campo col codice della regione? Mi trovo dati strani: per il lazio ho due zone/ordinanze diverse che iniziano entrambe il 15/3/2021 (elementi 163 e 192 del JSON), e poi il file areeStorico.json  contiene un numero di elementi diverso (258) da areeStorico.csv (243); forse nel CSV avete tolto appunto i dati errati?

**Comment by aborruso** [comment]
Ciao @jumpjack,
il file [areeStorico.json](https://github.com/ondata/covid19italia/blob/master/webservices/COVID-19Aree/processing/areeStorico.json) è quello che ci hai suggerito di creare.

È un estrazione grezza, a partire dal geojson, dopo la rimozione delle geometrie.

`AreeStorico.csv` è un file invece che in cui abbiamo applicato dei filtri. Ma quello di tuo interesse, quello grezzo è JSON che ci hai chiesto.

Il JSON ha per te dei problemi?

**Comment by jumpjack** [comment]
Nel JSON riscontro il problema che ho indicato prima, per il Lazio, le altre regioni non so. Ma non capisco se è un problema nel file originale, che è troppo lungo e complesso, non riesco ad esaminarlo a mano.

**Comment by jumpjack** [comment]
Qui c'è un elenco di tutte le ordinanze.... ma anche qui ho trovato vari errori:
https://www.openpolis.it/coronavirus-lelenco-completo-degli-atti/

Questo sito invece fa (anche) un grafico dei colori, ma non ho capito da dove prende i dati:
https://www.epimox.polimi.it/

**Comment by aborruso** [comment]
> per il lazio ho due zone/ordinanze diverse che iniziano entrambe il 15/3/2021 (elementi 163 e 192 del JSON)

Ciao, non è un errore. Il file è fatto così.

[Qui](https://github.com/pcm-dpc/COVID-19/issues/1045#issuecomment-809447063) trovi una mia domanda in merito e a seguire la risposta.

**Comment by aborruso** [comment]
chiudo
