### ISSUE TITLE
Aggiornamento AGENAS

### ISSUE THREAD

**Issue by Paulsword** [ondata/covid19italia#106]
Ciao,

sempre grazie per il lavoro svolto.
L'aggiornamento dei dati AGENAS è fermo al 19/5.
Mi chiedevo se fosse intenzionale, temporaneo, o accidentale.

Grazie molte
Paolo

**Comment by aborruso** [comment]
Buongiorno @Paulsword , la fonte dei dati era il problema, vedi https://twitter.com/ondatait/status/1395842697424945155

Ora dovrebbe essere ok e stasera dovrebbe ripartire. Aggiunti i dati del 21

**Comment by Paulsword** [comment]
Grazie
