### ISSUE TITLE
Automatizzare estrazione dati INFN-ISS + file "latest"

### ISSUE THREAD

**Issue by opencovid-mr** [ondata/covid19italia#109]
La dashboard INFN è stata aggiornata poche ore fa con nuovi dati.

Sarebbe interessante automatizzare l'estrazione per storicizzare i dati estratti.

Molto importante sarebbe avere a disposizione dei file con nome immutabile (eg. "blabla_latest.csv") per poterli riutilizzare altrove.

Ad esempio a partire dai CSV contenuti nella [cartella](https://github.com/ondata/covid19italia/tree/master/webservices/INFN_iss/processing/iss_opsan_italia)  con i casi sintomatici e ricoveri con distinzione tra operatori sanitari e altri è possibile stimare su scala regionale gli indici Rt_sintomi e Rt_ricoveri.

Si veda il progetto [Rt_Estimation](https://vienne.shinyapps.io/rt_estimation/) che attualmente lavora soltanto con i dati di Italia e Lombardia (gli unici fino a ieri disponibili).

Grazie come sempre del supporto.

**Comment by aborruso** [comment]
@opencovid-mr grazie.

Ho creato questi due file di insieme, in version wide e long:

- https://github.com/ondata/covid19italia/blob/master/webservices/INFN_iss/processing/iss_sintomatici_altri.csv
- https://github.com/ondata/covid19italia/blob/master/webservices/INFN_iss/processing/iss_sintomatici_altri_wide.csv
- https://github.com/ondata/covid19italia/blob/master/webservices/INFN_iss/processing/iss_sintomatici_opsan.csv
- https://github.com/ondata/covid19italia/blob/master/webservices/INFN_iss/processing/iss_sintomatici_opsan_wide.csv

Preferirei esporre pochi file di insieme e non "n" in tutte le combinazioni. Mi fai sapere se per voi va bene?

**Comment by opencovid-mr** [comment]
La soluzione con "pochi" file di insieme è perfetta e molto funzionale.

Grazie.

**Comment by opencovid-mr** [comment]
**Update**

I file oggetto di richiesta sono già disponibili

https://github.com/ondata/covid19italia/blob/master/webservices/INFN_iss/processing/iss_80plus.csv

- - - -

A seguito di un controllo di coerenza tra le varie fonti risulta che i dati del grafico 'Opetatori sanitari' non contengono tutti i casi riportati alla Sorveglianza Integrata Covid-19 ISS.  Probabilmente si tratta dei record nei quali il campo "Operatore Sanitario SI/NO" non viene valorizzato.

Sarebbe quindi utile avere a disposizione gli stessi file di insieme anche per i dati che alimentano il grafico 'Ultra-ottantenni', attualmente disponibili in JSON raw qui:

https://github.com/ondata/covid19italia/tree/master/webservices/INFN_iss/processing/iss_80plus

Anche i dati che alimentano quel grafico non saranno completi, in quanto anche il campo "età" può non essere valorizzato. Ma a prima vista risultano molto più completi rispetto a quelli del grafico 'Operatori Sanitari'.

Grazie.

**Comment by aborruso** [comment]
> Sarebbe quindi utile avere a disposizione gli stessi file di insieme anche per i dati che alimentano il grafico 'Ultra-ottantenni', attualmente disponibili in JSON raw qui:

ok, chiudo questa e apro nuova
