### ISSUE TITLE
API: schema dati provinciali

### ISSUE THREAD

**Issue by aborruso** [ondata/covid19italia#11]
Caro @patrunomeister ,
visto che alcuni dei nomi provincia pubblicati da Prot. Civ. sono errati, potresti inserire nello schema di output anche il codice ISTAT?

Lo trovi qui https://github.com/ondata/covid19italia/blob/master/publication/provinceArchivioISTAT.csv

Grazie

![image](https://user-images.githubusercontent.com/30607/76070529-fea13e00-5f94-11ea-8d5a-bef3edcd14fc.png)

**Comment by patrunomeister** [comment]
Certo! Dammi 30 secondi

Il ven 6 mar 2020, 10:28 Andrea Borruso <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
Non appena lo fai, chiudi tu la issue e grazie!
