### ISSUE TITLE
Estrarre dati grafico 'Ultra-ottantenni'

### ISSUE THREAD

**Issue by aborruso** [ondata/covid19italia#110]
A seguito di un controllo di coerenza tra le varie fonti risulta che i dati del grafico 'Opetatori sanitari' non contengono tutti i casi riportati alla Sorveglianza Integrata Covid-19 ISS.  Probabilmente si tratta dei record nei quali il campo "Operatore Sanitario SI/NO" non viene valorizzato.

Sarebbe quindi utile avere a disposizione gli stessi file di insieme anche per i dati che alimentano il grafico 'Ultra-ottantenni', attualmente disponibili in JSON raw qui:

https://github.com/ondata/covid19italia/tree/master/webservices/INFN_iss/processing/iss_80plus

Anche i dati che alimentano quel grafico non saranno completi, in quanto anche il campo "età" può non essere valorizzato. Ma a prima vista risultano molto più completi rispetto a quelli del grafico 'Operatori Sanitari'.

Grazie.

_Originally posted by @opencovid-mr in https://github.com/ondata/covid19italia/issues/109#issuecomment-884901134_

**Comment by aborruso** [comment]
@opencovid-mr dimmi se sono questi due:

- https://github.com/ondata/covid19italia/blob/master/webservices/INFN_iss/processing/iss_80plus_altri_wide.csv
- https://github.com/ondata/covid19italia/blob/master/webservices/INFN_iss/processing/iss_80plus_wide.csv

**Comment by opencovid-mr** [comment]
Conferma, scusa del disturbo.
