### ISSUE TITLE
Fetching dati posti letto da sito Agenas

### ISSUE THREAD

**Issue by jumpjack** [ondata/covid19italia#115]
Il servizio non funziona più? I dati risultano aggiornati a  diversi mesi fa:
covid19italia/webservices/agenas/processing/

Altre fonti ne conoscete?
Sto setacciando github ma non trovo nessuno che registri i 3 dati che determinino i colori delle regioni, nè trovo un database ufficiale dei posti letto disponibili in ordinaria e intensiva.

**Comment by aborruso** [comment]
Ciao @jumpjack  forse non ho compreso bene: vedo i dati fino a ieri
Se non ho capito, per favore mi dai qualche dettaglio in più?

![image](https://user-images.githubusercontent.com/30607/133407208-ebde9eb7-0f05-4699-93c2-92cdb54736d3.png)

**Comment by jumpjack** [comment]
no sono io che non capisco.... ogni volta che apro la pagina vedo dati diversi!
Forse è un problema di connessione lenta, pagina lunga, e mancanza di un marcatore di fine pagina...

Chiudo,  che è meglio. :-)
