### ISSUE TITLE
Errore colore friuli venezia giulia da 29/11/2021

### ISSUE THREAD

**Issue by jumpjack** [ondata/covid19italia#116]
A causa di [questo errore](https://github.com/pcm-dpc/COVID-19/issues/1191) nel file di origine, anche il [vostro file areeStorico.json](https://raw.githubusercontent.com/ondata/covid19italia/master/webservices/COVID-19Aree/processing/areeStorico.json) è sbagliato:  sembra che il Firuli sia in zona gialla da aprile invece che da novembre:

![image](https://user-images.githubusercontent.com/1620953/143922375-11ed2683-d31a-403d-8027-035cb4e6dc8a.png)

**Comment by aborruso** [comment]
Grazie @jumpjack 

Non appena possibile vediamo di correggere

**Comment by jumpjack** [comment]
Hanno sistemato.
