### ISSUE TITLE
Vaccinati per età e comune in Lombardia | Esistono dati?

### ISSUE THREAD

**Issue by Leobarb** [ondata/covid19italia#119]
Ciao,

per caso sono disponibili i dati sulla copertura vaccinale per fascia di età per ogni comune lombardo?
Qua su Github vedo solo lo storico del numero di vaccinati in ogni comune, ma senza distinzioni di età o genere.

Grazie mille!

**Comment by aborruso** [comment]
Ciao @Leobarb ,
dati in formato machine readable non credo ce ne siano.

La regione credo che pubblichi soltanto una dashboard https://www.regione.lombardia.it/wps/portal/istituzionale/HP/vaccinazionicovid/dashboard-vaccini-territorio

Proviamo a fare richiesta.

**Comment by aborruso** [comment]
In realtà non ci sono nemmeno lì le fasce
