### ISSUE TITLE
Le API su openpuglia.org non ritornano l'header content-type corretto

### ISSUE THREAD

**Issue by napolux** [ondata/covid19italia#12]
https://openpuglia.org/api/?q=getdatacovid-19&reg=lombardia

Ritorna un header sbagliato: 

<img width="285" alt="Schermata 2020-03-06 alle 10 38 47" src="https://user-images.githubusercontent.com/1070836/76071530-b4b95780-5f96-11ea-9613-ee5f57f571dd.png">

Il `Content-Type` dovrebbe essere `application/json`

**Comment by aborruso** [comment]
@patrunomeister appena puoi, è per te
