### ISSUE TITLE
Cartella Agenas

### ISSUE THREAD

**Issue by RossoDeM** [ondata/covid19italia#121]
Buongiorno,
ultime tabelle ferme al 01.10
Dati non più disponibili o problema tecnico?
Grazie

**Comment by vi-enne** [comment]
Confermo.
Le actions pero non stanno fallendo e il log sembra estrarre i dati corretti.
Non sono riuscito a risalire al problema.

Edit: pare non trovare il percorso dove salvare i dati
https://github.com/ondata/covid19italia/actions/runs/3189630627/jobs/5203658938#step:4:160

**Comment by aborruso** [comment]
Grazie @RossoDeM e @vi-enne , è sorto un bug con l'ultima versione di VisiData.

Quindi ho forzato la versione in fase di installazione, a una precedente https://github.com/ondata/covid19italia/commit/05019cdb945e25744624fa62aa552a6a7fa2f685

Ora sembra funzionare tutto.

Grazie ancora

**Comment by RossoDeM** [comment]
Grazie a entrambi, @aborruso e @vi-enne
