### ISSUE TITLE
Emilia Romagna con e senza trattino

### ISSUE THREAD

**Issue by pigreco** [ondata/covid19italia#23]
Segnalo che in questo file:

https://github.com/ondata/covid19italia/blob/master/publication/riepilogoArchivio_storico.csv

`Emilia Romagna` è presente in due modalità: con e senza trattino.

- `Emilia Romagna`
- `Emialia-Romagna`

per verificare, cercate `Emilia`

**Comment by fmossott** [comment]
Questa issue può essere chiusa

**Comment by aborruso** [comment]
grazie @fmossott
