### ISSUE TITLE
[API] regione 'Novara' in ?q=getdatacovid-19

### ISSUE THREAD

**Issue by floatingpurr** [ondata/covid19italia#24]
**Regione 'Novara' in `?q=getdatacovid-19`**
Questa chiamata ritorna nella lista il seguente oggetto:

```json
{
"provincia":"Alessandria",
"numero infetti":"32",
"regione":"Novara",
"data":"2020-03-06",
"codice provincia":"006"
}
```

**Come riprodurlo**
HTTP GET: [https://openpuglia.org/api/?q=getdatacovid-19](https://openpuglia.org/api/?q=getdatacovid-19)

**Risultato atteso**
"regione":"Piemonte",

**Screenshots**
n/a

**Altre informazioni**
n/a

**Comment by patrunomeister** [comment]
Fatto. E' stato un problema sul file protezione civile
