### ISSUE TITLE
Aggiunta dati dal 19 Febbraio e nazionali non attribuibili ad una regione fino al 1 Marzo

### ISSUE THREAD

**Issue by fmossott** [ondata/covid19italia#27]
**Se la tua richiesta è relativa ad un problema descrivicela per favore.**

- Attraverso i comunicati stampa ho raccolto i dati fin dal 19 Febbraio, si potrebbero aggiungere
- Per il periodo dal 19 Febbraio al 1 Marzo, solo i dati sul numero totale di casi erano disponibili a livello regionale, gli altri sono disponibili a livello nazionale, ma mancano nel csv

**Descrivi la soluzione che ti piacerebbe**

- Ho aggiunto i dati per il periodo mancante
- Ho inserito i dati non attribuibili ad una regione in una nuova riga con regione "Sconosciuta"

**Descrivi le alternative considerate**
Come modellizzazione non vedo alternative, ma ovviamente per il nome della regione indeterminata esistono infinite possibilità

**Altro materiale**
[DataStudio](http://bit.ly/ConavirusItaliaDataStudio)
[Spreadsheet](http://bit.ly/CoronaVirusItalia)

**Comment by aborruso** [comment]
Grazie mille
