### ISSUE TITLE
Lavori derivati

### ISSUE THREAD

**Issue by rainbowbreeze** [ondata/covid19italia#3]
Grazie per i CSV!

Per mia consultazione personale, importo il CSV automaticamente in un Google Sheets ogni giorno (https://docs.google.com/spreadsheets/d/1OaZic5DVNp-tgg2GMnQlQXaCB7r_KSdu2WuZiD8B3kg/edit#gid=1287960954), e ho calcolato la differenza dei contagi per provincia.

Quindi, ci ho costruito sopra una piccola dashboard: https://datastudio.google.com/s/pkXn62iU3rQ

**Comment by aborruso** [comment]
Ciao @rainbowbreeze sei stato di ispirazione per una sezione dedicata https://github.com/ondata/covid19italia#chi-usa-questi-dati

Grazie

**Comment by nickprock** [comment]
@aborruso segnalo la shiny dashboard di Helthy Reply a cura di Marco Cortese @MarCortese (sta ancora fixando alcuni bug) il link è questo:
https://marcocortese.shinyapps.io/Covid-19Italia/

**Comment by aborruso** [comment]
grazie @nickprock ma è derivato non da questo repo, perché ormai non ha più motivo di esistere (c'è il repo ufficiale).
