### ISSUE TITLE
I dati sul COVIDー19 di Protezione Civile sono esposti anche come Web Map Service

### ISSUE THREAD

**Issue by aborruso** [ondata/covid19italia#30]
- https://services6.arcgis.com/L1SotImj1AAZY1eK/ArcGIS/rest/services/COVID19_Province/FeatureServer
- https://services6.arcgis.com/L1SotImj1AAZY1eK/ArcGIS/rest/services/COVID19_AREE/FeatureServer
- https://services6.arcgis.com/L1SotImj1AAZY1eK/ArcGIS/rest/services/COVID19_andamento/FeatureServer
- https://services6.arcgis.com/L1SotImj1AAZY1eK/ArcGIS/rest/services/COVID19__Regioni/FeatureServer

**Comment by pigreco** [comment]
Grazie mille per la dritta @aborruso 

![image](https://user-images.githubusercontent.com/7631137/76146874-25479d80-6097-11ea-8ef1-63344b81cb08.png)
