### ISSUE TITLE
Lavoro derivato: codice su iodide

### ISSUE THREAD

**Issue by visika** [ondata/covid19italia#34]
Ciao, ho creato una pagina navigabile da chiunque tramite browser!
Si trova qui: https://alpha.iodide.io/notebooks/4249/
È un po' lentino nell'importare i pacchetti ma poi va abbastanza liscio.
Sarei contento se può essere di aiuto a qualcuno che non ha la competenza o la voglia di installare programmi di analisi sulla propria macchina.

**Comment by pieroit** [comment]
Bello!
