### ISSUE TITLE
Errato numero positivi nel comune visualizzato quando si clicca sul punto sulla mappa lombarda.

### ISSUE THREAD

**Issue by LucaMare2** [ondata/covid19italia#35]
Buongiorno e grazie mille per il vostro lavoro! Non sono esperto di github e spero di stare seguendo la procedura corretta. Seguo lo schema proposto da github per la segnalazione dei bug.

**Descrizione del bug**
Quando apro la mappa relativa ai dati di Regione Lombardia (https://github.com/ondata/covid19italia/blob/master/webservices/regioneLombardia/rawdata/ta_covid19_comuni_time.geojson), il numero dei casi presenti nel comune è correttamente indicato dal numero nel punto blu. Se clicco sul punto blu mi si apre una tenda con diverse informazione relative al comune. Il numero dei positivi, però, non coincide con quello nel punto blu visualizzato nella visione generale della mappa.

**Come riprodurlo**
I passi per riprodurlo:
1. Andare su https://github.com/ondata/covid19italia/blob/master/webservices/regioneLombardia/rawdata/ta_covid19_comuni_time.geojson
2. Scegliere un comune, zoommare fino a vedere i punti blu relativi ai singoli comuni 
3. Cliccare sul punto blu per vedere la visualizzazione a tenda
4. Il numero dei positivi nella visualizzazione a tenda è diverso da quello mostrato nel punto blu

**Risultato atteso**
Credo che il numero dei positivi dovrebbe coincidere nell'intenzione dei creatori della mappa.

**Screenshots**
![Brembate](https://user-images.githubusercontent.com/56926511/76681709-309a4c00-65f6-11ea-9ecd-db9f48963c42.PNG)
![Brembate2](https://user-images.githubusercontent.com/56926511/76681714-37c15a00-65f6-11ea-9c8c-43d19aa03d4f.PNG)

**Comment by aborruso** [comment]
Ciao @LucaMare2 la mappa viene creata automaticamente, perché il dato è in formato geografico: geojson.
La mappa non è una nostra produzione.

Il numero che vedi nel pallino, corrisponde al numero di righe di informazioni per quella coppia di coordinate. È una serie temporale, quindi per lo stesso punto `n` informazioni nel tempo

Se vuoi vedere la tabella non come mappa, ma come dati è questa https://github.com/ondata/covid19italia/blob/master/webservices/regioneLombardia/processing/TA_COVID19_RL.csv
