### ISSUE TITLE
Dati per comune

### ISSUE THREAD

**Issue by Recursing** [ondata/covid19italia#36]
Per caso esiste una fonte più "ufficiale" dei dati per comune? Idealmente non limitati alla regione Lombardia

Ho trovato solo questo https://github.com/ondata/covid19italia/tree/master/webservices/regioneLombardia , per caso sono raccolti anche altrove?

Che voi sappiate ci sono mappe della diffusione dell'epidemia nei vari comuni?

Grazie mille per il lavoro

**Comment by aborruso** [comment]
CIao @Recursing quello della regione Lombardia è soltanto un caso.

L'ISS ha quei dati ma al momento pubblicamente consultabili in PDF come questo https://www.epicentro.iss.it/coronavirus/bollettino/Bolletino-sorveglianza-integrata-COVID-19_19-marzo-2020_appendix.pdf

**Comment by Recursing** [comment]
:( fatemi sapere, ho paura chiudano quella fonte

**Comment by Recursing** [comment]
@aborruso scusa ancora il disturbo, per caso sai anche se da qualche parte si può trovare il numero di tamponi (con esito positivo o negativo), per provincia lombarda? A chi mi conviene chiedere?

Meno importante, per caso sapete anche perché non pubblicano dati per comune in un formato più parsabile del pdf?

Scusate davvero il disturbo ma non so a chi rivolgermi

**Comment by aborruso** [comment]
@Recursing non disturbi.

L'Istituto Superiore di Sanità e la Regione Lombardia dovrebbero avere i dati che cerchi. Purtroppo so che non è una risposta che ti è di grande aiuto
