### ISSUE TITLE
Important information which is missing

### ISSUE THREAD

**Issue by ustajan** [ondata/covid19italia#37]
Folks, an important information that unfortunately is missing in most data sets is the **total number of COVID-19 tests performed.** Without this it is not entirely clear whether changes in numbers are due to increase in illnesses or more widespread testing.  If one could find this information it would be highly valuable in determining the actual dynamics of the disease.

**Comment by Recursing** [comment]
You can find it in the official repo of the Protezione Civile
https://github.com/pcm-dpc/COVID-19/ yesterday the number was 206886
