### ISSUE TITLE
Storico da Febbraio 25

### ISSUE THREAD

**Issue by carlotorniai** [ondata/covid19italia#4]
Sarebbe fantastico se riusciste a recuperare lo storico dei vari update via file dall'inizio per avere un archivio completo. Bel lavoro , molto utile!

**Comment by aborruso** [comment]
Ciao @carlotorniai e grazie per il tuo riscontro, che proveremo a trasformare in azione.

E se vuoi unirti, sarebbe un piacere.

Abbiamo inserito il tuo repo a tema in questa lista https://github.com/ondata/covid19italia#altri-progetti-a-tema

**Comment by ebucci72** [comment]
Buongiorno! Intanto complimenti per lo sforzo di rendere pubblici questi dati. Posso chiedere a cosa si riferiscono? Per esempio, i morti in regione lombardia (che sono molti di più dei morti per coronavirus attualmente registrati) cosa sono?

**Comment by aborruso** [comment]
Ciao @ebucci72 sono i morti per corona virus che trovi nel report di protezione civile http://www.protezionecivile.gov.it/documents/20182/1221364/Dati+Riepilogo+Nazionale+4marzo2020/33cdddf7-006d-4489-a7fb-ce1ea604fee3

Sono numeri per cui la Prot. Civ. scrive che potranno

>essere confermati solo dopo che l’Istituto Superiore di Sanità avrà stabilito la causa effettiva del decesso.

**Comment by ebucci72** [comment]
Ma non sono quelli! nella tabella che riporti, per esempio, per la Lombardia sono indicati 73 deceduti (su un totale di 107 in tutta italia); nel file csv su github, io per la sola lombardia vedo 150 deceduti al 4 marzo ... e così via anche per gli altri valori

**Comment by aborruso** [comment]
Ciao @ebucci72 io nel file [CSV](https://github.com/ondata/covid19italia/blob/master/publication/riepilogoArchivio.csv) ne vedo 73.

Ma forse non ho compreso. 

![image](https://user-images.githubusercontent.com/30607/75982465-060a0e00-5ee7-11ea-9449-f2a833c7a54b.png)

**Comment by ebucci72** [comment]
Ok grazie. Errore mio: shift di colonna. Grazie!

**Comment by aborruso** [comment]
@carlotorniai la chiudo, perché stiamo integrando i dati di @alessiodl (vedi #10 )
