### ISSUE TITLE
COMUNI_COVID19.geojson corrotto

### ISSUE THREAD

**Issue by Nicola9016** [ondata/covid19italia#42]
**Describe the bug**
Il file risulta corrotto, out of memory e quindi non si riesce ad utilizzare. Idem per il cdv che è fermo a 4 giorni fa.

**Comment by aborruso** [comment]
Grazie @Nicola9016 , aggiornati.

Purtroppo il server sorgente alle volte va in affanno. Appeno posso devo inserire un controllo che prova a scaricarlo alcune volte, sinché non risponde correttamente
