### ISSUE TITLE
Dato del 13 aprile errato

### ISSUE THREAD

**Issue by Stigni** [ondata/covid19italia#44]
Il processo automatico di scarico dei dati ha girato alle 20:00 mentre Regione Lombardia ha rilasciato i dati alle 20:30. Quindi i dati scaricati con la reference date odierna sono identici a quelli di ieri.

PS sto utilizzando i dati che staricate giornalmente per una serie di analisi sui tamponi che potete travare sul mio account twitter: https://twitter.com/Stigni

**Comment by aborruso** [comment]
Ciao @Stigni li ho aggioranti.

Mi fa piacere che utilizzi i dati ;)
