### ISSUE TITLE
Dati incompleti: TA_COVID19_RL.json 

### ISSUE THREAD

**Issue by Stigni** [ondata/covid19italia#45]
Ho notato che il dato il presente nel json in oggetto è parziale e riporta soltanto 2000 record. E' possibile effettuare lo scarico completo?

Ho provato a dare un occhio al programma .sh per lanciarlo in autonomia ma mi sa che mi manca qualche pezzo.

Davide

**Comment by aborruso** [comment]
@Stigni grazie mille, dovrei avere corretto. Qui l'output https://github.com/ondata/covid19italia/blob/master/webservices/regioneLombardia/processing/TA_COVID19_RL.csv

Ti chiedo due cortesie:

- verifica se l'output ti sembra ok, e nel caso chiudi l'issue;
- mi scrivi una descrizione di questa tabella (una frase per definirla, non uno schema dati)?

Grazie

**Comment by Stigni** [comment]
Perfetto.

La tabella contiene i dati dei positivi (età, nazionalità, comune di domicilio/residenza), la data del tampone positivo e se il paziente è Vivo o deceduto.
