### ISSUE TITLE
[shapefile]

### ISSUE THREAD

**Issue by beriapaolo** [ondata/covid19italia#47]
Ho associato il dato al codice comunale di uno shapefile di comuni, in modo da poter mappare il dato. Ve lo allego.

I due excel sono 
1) i dati originali per singola osservazione con in più il PRO_COM corretto (cioè coerente con lo shapefile per il join)
2) la somma di deceduti e vivi associata al comune
Ci sono un po' di osservazioni perse, senza procom.

Lo shapefile contiene i comuni lombardi al 2018, con il dato di vivi e morti (l'excel 2). Essendo solo i comuni lombardi, sono esclusi i pochi dati esterni, che comunque sono presenti nell'excel.

Paolo
[TA_COVID19_RL shapefile.zip](https://github.com/ondata/covid19italia/files/4498550/TA_COVID19_RL.shapefile.zip)

**Comment by aborruso** [comment]
Ciao @beriapaolo e grazie.

Nel file CSV che abbiamo pubblicato sembra che per ogni codice comune ci sia da rimuove un `3` a inizio cella.

Per Bergamo ad esempio è `3016024`, mentre il codice ISTAT è `016024`. Che ne pensi se aggiungo  nel CSV una colonna `PRO_COM_T`?

**Comment by beriapaolo** [comment]
Sì, il 3 è il codice istat della Regione lombardia. Io ho dovuto ricodificare un po' perchè lo shapefile è del 2018 e perchè ogni tanto si perdono gli zeri, tipo iIl PRO_COM di Bergamo era 16024.  
Comunuque sì, la colonna _T è utile per tutti per rifarlo.

**Comment by aborruso** [comment]
Ciao @beriapaolo ho aggiunto nel CSV la colonna `PRO_COM_T`. 

Posso aggiungere lo shapefile che ci hai inviato, ma se è un semplice JOIN, non mi sembra necessario inserirlo, perché è una cosa (che grazie alla tua nota) può essere realizzate appunto via JOIN tra CSV e file geografico.

Invece metterei nel README un link al tweet con la tua onedotmap

**Comment by aborruso** [comment]
Ti ho inserito nel README https://github.com/ondata/covid19italia/tree/master/webservices/regioneLombardia#elaborazioni-derivate

**Comment by beriapaolo** [comment]
Sì, è un'elaborazione molto semplice, ma il JOIN non è fatto sul singolo dato del vostro database, ma sulla somma di deceduti e vivi per comune. Cioè l'oggetto grafico "comune" ha due campi in più, "vivi" e "morti". Roba da mezz'ora in totale, ma avendola già fatta... Comunque come preferite.

**Comment by aborruso** [comment]
@beriapaolo ho inserito gli shapefile in una cartella di questo repo e ne ho dato notizia anche nel README che ho aggiornato https://github.com/ondata/covid19italia/tree/master/webservices/regioneLombardia#elaborazioni-derivate

Grazie

**Comment by beriapaolo** [comment]
Figurati, ancora grazie a voi.
