### ISSUE TITLE
Problema con gli INCR_DATE_PRV_TAMP_RL_v2

### ISSUE THREAD

**Issue by Spazio2001** [ondata/covid19italia#49]
Da due giorni la somma dei dati giornalieri di INCR_DATE_PRV_TAMP_RL_v2 non corrisponde più con quella comunicata dalla regione. È possibile che una parte dell'archivio non venga scaricato correttamente?

**Comment by aborruso** [comment]
Ciao @Spazio2001 e grazie per la notifica.

Io faccio la query sul layer provinciale, mentre sul sito è esposta quella per regione. I valori restituiti dal server espongono totali diversi.

Per ora mi fermo a questa nota, ma provo ad approfondire

**Comment by aborruso** [comment]
Ciao @Spazio2001 ,
la [query](https://services1.arcgis.com/XannvQVnsM1hoZyv/ArcGIS/rest/services/INCR_DATE_PRV_TAMP_RL_v2/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=true&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=) sui dati provinciali restituisce in questo momento 1257 record.

![image](https://user-images.githubusercontent.com/30607/83330918-c5762280-a292-11ea-8b78-6c989eb8df7d.png)

La [query](https://services1.arcgis.com/XannvQVnsM1hoZyv/ArcGIS/rest/services/INCR_DATE_PRV_TAMP_RL_v2/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=) che uso per il giornaliero provinciale produce un JSON che al momento restituisce un totale 88315 tamponi.

Al momento la dashboard, pescando dal layer regionale, restituisce un valore più alto, come se alle "mie" province ci fosse da aggiungere altro.

Quello che potevo fare era verificare i dati alla fonte. Sul perché alla fonte ci siano differenze purtroppo non posso sapere :(

![image](https://user-images.githubusercontent.com/30607/83330992-4503f180-a293-11ea-8a94-87a1632e50e5.png)
