### ISSUE TITLE
generare tabella con nomi regioni usati da prot. civ. e codice regioni ISTAT

### ISSUE THREAD

**Issue by aborruso** [ondata/covid19italia#5]

**Comment by pigreco** [comment]
Non sono sicuro di aver capito, ho estratto dal file di questo repo le Regioni e messo il codice ISTAT:


regione | codiceISTAT
-- | --
PIEMONTE | 01
LOMBARDIA | 03
TRENTINO ALTO ADIGE | 04
VENETO | 05
FRIULI VENEZIA GIULIA | 06
LIGURIA | 07
EMILIA-ROMAGNA | 08
TOSCANA | 09
UMBRIA | 10
MARCHE | 11
Pesaro | 11
LAZIO | 12
ABRUZZO | 13
MOLISE | 14
CAMPANIA | 15
PUGLIA | 16
BASILICATA | 17
CALABRIA | 18
SICILIA | 19
SARDEGNA | 20

**Comment by aborruso** [comment]
Sono stato poco chiaro io: dal file di riepilogo in CSV (nella cartella pubblication), i valori univoci di regione per come appaiano, e associarli ai codici ISTAT

Grazie

**Comment by pigreco** [comment]
> Sono stato poco chiaro io: dal file di riepilogo in CSV (nella cartella pubblication), i valori univoci di regione per come appaiano, e associarli ai codici ISTAT
> 
> Grazie

Allora ho capito bene, la tabella di sopra è quella.

**Comment by pigreco** [comment]
Caro @aborruso finalmente ho capito, ecco il file:


codiceISTAT | Regione
-- | --
01 | Piemonte
02 | Valle d'Aosta
03 | Lombardia
04 | Trento
04 | Bolzano
05 | Veneto
06 | Friuli V.G.
07 | Liguria
08 | Emilia Romagna
09 | Toscana
10 | Umbria
11 | Marche
12 | Lazio
13 | Abruzzo
14 | Molise
15 | Campania
16 | Puglia
17 | Basilicata
18 | Calabria
19 | Sicilia
20 | Sardegna

**Comment by aborruso** [comment]
Grazie Mille Totò
