### ISSUE TITLE
Errore Could not connect su endpoint openpuglia.org

### ISSUE THREAD

**Issue by vincenzo-scia** [ondata/covid19italia#51]
Ciao a tutti,
l'endpoint [https://openpuglia.org/api/](https://openpuglia.org/api/?q=getdatapccovid-19) sembra aver smesso di funzionare, è possibile fare qualcosa per ripristinarlo?

**Come riprodurlo**
I passi per riprodurlo:
1. Aprire Postman o un qualsiasi client per effettuare chiamate REST
2. Effettuare una GET verso `https://openpuglia.org/api/?q=getdatapccovid-19`
3. Errore restituito `Could not connect`

**Risultato atteso**
Una response contenente un JSON con i dati nazionali.

**Altre informazioni**
 - Client REST: Postman 7.26.0

Grazie mille

**Comment by aborruso** [comment]
Ciao @patrunomeister , è per te

Grazie
