### ISSUE TITLE
Immuni

### ISSUE THREAD

**Issue by Spazio2001** [ondata/covid19italia#55]
Ho visto che sul sito di Immuni c'è ora una dashboard con alcuni dati.

Si potrebbero estrarre quotidianamente i dati? Sulle notifiche inviate e gli utenti positivi infatti non c'è lo storico, come per l'altro. 

https://www.immuni.italia.it/dashboard.html

Grazie per tutto il lavoro che fate.

**Comment by aborruso** [comment]
Ecco un primo output https://github.com/ondata/covid19italia/blob/master/webservices/immuni/processing/immuni.csv

Vediamo se la cosa procede bene da domani.

Grazie

**Comment by aborruso** [comment]
Il sistema funziona. Il dato a monte non sembra aggiornato giornalmente.

Per il momento lo raccogliamo una volta al giorno, tanto tra i dati c'è sia la data in cui è eseguito lo scraping, che il loro metadato su ultimo aggiornamento.
