### ISSUE TITLE
errore nei dati di napoli?

### ISSUE THREAD

**Issue by raymanrt** [ondata/covid19italia#6]
Ciao, stavo guardando il file: https://raw.githubusercontent.com/ondata/covid19italia/master/publication/provinceArchivio.csv

Mi sembra scorretto che il numero per NAPOLI del 3 Marzo (30) sia più alto del numero del 4 Marzo (17), ho capito male qualcosa io?

**Comment by aborruso** [comment]
Ciao @raymanrt ,
se guardi i [PDF relativi](https://github.com/ondata/covid19italia/tree/master/pdfArchive) e guardi anche il CSV, vedi che la protezione Civile è passata dal solo valore `Napoli` a due valori `Napoli` e `Campania da aggiornare`.

Spero di essermi spiegato

**Comment by raymanrt** [comment]
Ciao, grazie della velocità.

Guardando il pdf in effetti capisco che il dato è estratto nel modo corretto.

Tuttavia non capisco bene quale sia il significato di questo "da aggiornare". Vale anche per "in fase di verifica e aggiornamento".

Praticamente può significare che i dati del giorno precedente erano sbagliati? Magari che facendo controlli più approfonditi si sono resi conto che il dato era sbagliato?

(P.S. è giusto che ne discutiamo qui o c'è un canale più appropriato?)

**Comment by aborruso** [comment]
Ciao @raymanrt noi qui possiamo darti soltanto un'opinione :(

La domanda va fatta alla Protezione Civile.

Per me vuol dire che hanno nuove info sui dati, o dati migliori, su cui stanno lavorando e per i quali devono inserire l'attributo "provincia", ma di cui sanno già che non è più applicabile con certezza l'attributo del giorno prima. Qui parlo del caso Napoli.

**Comment by raymanrt** [comment]
grazie comunque dell'ottimo lavoro che state facendo
