### ISSUE TITLE
Ripetizioni dati

### ISSUE THREAD

**Issue by cipodroid85** [ondata/covid19italia#61]
Ciao a tutti,
ho fatto un piccolo lo progetto con c#  per monitorare i numeri dell'ultima ondata
e mi sono accorto che il totale decessi giornalieri e uguale al totale decessi

I passi per riprodurlo:
1. Aprire Postman
2. effettuare una GET verso l'API  https://openpuglia.org/api/?q=getdatapccovid-19
3. confrontare i valori  di totale deceduti e deceduti giornalieri.

**Risultato atteso**
due valori diversi

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/48394843/99057822-959aad00-259c-11eb-9fdc-5067a49c302c.png)

**Altre informazioni**
Ad esempio il sistema su cui si verifica.
 - OS: Windows 10
 - linguaggio : c#
- ambiente : .NET

**Comment by patrunomeister** [comment]
Grazie della segnalazione. provvedo a fare le correzioni necessarie. L'output corretto al momento è questo https://openpuglia.org/api/?q=getdatapccovid-19&reg=LAZIO&mode=ts&lang=it 
Devo ancora fare qualche correzione per avere il dato per tutte le regioni

**Comment by patrunomeister** [comment]
ok risolto. Scusa il ritardo

**Comment by cipodroid85** [comment]
Grazie a te per la tempestività, molto gentile.
Saluti✌️

Il sab 14 nov 2020, 20:44 Vincenzo Patruno <notifications@github.com> ha
scritto:
