### ISSUE TITLE
Dati incompleti

### ISSUE THREAD

**Issue by cipodroid85** [ondata/covid19italia#63]
ok risolto. Scusa il ritardo

_Originally posted by @patrunomeister in https://github.com/ondata/covid19italia/issues/61#issuecomment-727256173_

Ciao, scusa  ancora,
Ho provato poco fa l'API in questione ma i dati che mi restituisce sono solo quelli della Valle d'Aosta e sono tutti a zero  tranne la data che è sballata
![Screenshot (4)](https://user-images.githubusercontent.com/48394843/99235898-bf4f1080-27f6-11eb-9729-40f5d943e7a3.png)

**Comment by aborruso** [comment]
@cipodroid85 lo stato delle cose è ancora questo?

Grazie

**Comment by aborruso** [comment]
Immagino sia risolto, chiudo
