### ISSUE TITLE
Aiuto alla lettura dei dati

### ISSUE THREAD

**Issue by ffxx68** [ondata/covid19italia#64]
Sarebbe utile avere nel Readme una descrizione un po' più dettagliata di cosa rappresentano i dati estratti.
Intendo dire che non riesco a capire cosa rappresentino nel file finale (raw_Incidenza e raw_Numerocasi; quelli indipendenti dalla data) le varie colonne: ID, classe, ecc. 
Gran lavoro comunque! Grazie!

**Comment by aborruso** [comment]
Ciao @ffxx68 in settimana sarà fatto, hai pienamente ragione

**Comment by ffxx68** [comment]
Perfetto. Grazie!

**Comment by ffxx68** [comment]
Ulteriore richiesta... se possibile !

**Comment by aborruso** [comment]
@ffxx68 vai

**Comment by ffxx68** [comment]
Sarebbe fatibile estrarre i dati anche del grafico "Curva epidemica ..." (quello principale)?
Sto trafficando con scrape, jq e mlr ma non è affatto banale, non conoscendo gli strumenti.

**Comment by aborruso** [comment]
Ciao @ffxx68 ma i dati che cerchi non sono questi https://github.com/ondata/covid19italia/blob/master/webservices/iss_epicentro/processing/2020-11-19_curvaEpidemicaInizio.csv ?

Si trovano qui https://github.com/ondata/covid19italia/tree/master/webservices/iss_epicentro/processing

**Comment by ffxx68** [comment]
Esattamente... non lo vedevo perché mi aspettavo i file correnti (completo e ultimi 30gg) senza la data nel nome.
Noto nello script che il file corrente viene generato ma resta in rawdata/ 
Non sarebbe possibile copiare anche questi in processing/, oltre a storicizzarli con la data?
Ah, comunque, sto cercando di ripercorrere il calcolo di Rt eseguito dal'ISS settimanalmente, a partire da questi dati e con il metodo da loro utilizzato (https://www.iss.it/primo-piano/-/asset_publisher/o4oGR9qmvUz9/content/id/5477037?fbclid=IwAR0iprbfWY_8VJYdLBvw2M7DdPvhy0kFRHZOtFTAdfzkYjas5__YWLFTEIw)

**Comment by opencovid-mr** [comment]
> Ah, comunque, sto cercando di ripercorrere il calcolo di Rt eseguito dal'ISS settimanalmente, a partire da questi dati e con il metodo da loro utilizzato (https://www.iss.it/primo-piano/-/asset_publisher/o4oGR9qmvUz9/content/id/5477037?fbclid=IwAR0iprbfWY_8VJYdLBvw2M7DdPvhy0kFRHZOtFTAdfzkYjas5__YWLFTEIw)

Per un tentativo di riprodurre al meglio la stima di Rt si veda ad esempio [Rt_Estimation](https://vienne.shinyapps.io/rt_estimation/) applicazione in R basata su [EpiEstim](https://cran.r-project.org/web/packages/EpiEstim/index.html). Selezionando "Data to use: Italia" il dataset in input è l'ultimo disponibile tra quelli estratti da onData.

Per quanto riguarda fattibilità e limiti della riproduzione in proprio della stima di Rt a partire dai dati della Dashboard ISS occorre ricordare che ci sono da almeno due elementi da tenere in considerazione:

- i casi importati, che devono essere considerati in maniera opportuna. Come recentemente chiarito dall’Istituto Superiore di Sanità in una nota metodologica essendo casi importati devono essere contati tra i potenziali infettori di nuovi casi locali, ma non tra i casi che hanno contratto l’infezione localmente.
- il Serial Interval e cioè l’intervallo di tempo tra la data inizio sintomi di un caso indice e la data inizio sintomi dei casi secondari ad esso legati. La distribuzione del Serial Interval è di fondamentale importanza e come mostrato in questo recente articolo pubblicato su Science potrebbe variare anche sensibilmente da contesto a contesto e soprattutto potrebbe variare nel tempo

(tratto da ["Erreti (leggermente) maggiore di uno"](https://opencoviditaly.netsons.org/erreti-leggermente-maggiore-di-uno/))

**Comment by ffxx68** [comment]
Grazie per il prezioso contributo!
