### ISSUE TITLE
Aggiunta campo Dashboard ISS - necessità modifica script scraping

### ISSUE THREAD

**Issue by opencovid-mr** [ondata/covid19italia#67]
**Describe the bug**
Aggiutna campo Dashboard ISS (sezione INIZIO)

ISS dal 7 dicembre ha aggiunto un dataset di sintomatici oltre a quello già esistente, per le ragioni ipotizzate qui:
https://twitter.com/OpencovidM/status/1336086146431000581

**Risultato atteso**
A partire dal file 
https://github.com/ondata/covid19italia/blob/master/webservices/iss_epicentro/processing/2020-12-07_curvaEpidemicaInizio.csv
è necessari aggiungere una nuova colonna dal momento che ora i dataset sono tre.

**Comment by opencovid-mr** [comment]
File corretto da sostituire all'attuale del 7 dicembre

[2020-12-07_curvaEpidemicaInizio.zip](https://github.com/ondata/covid19italia/files/5658855/2020-12-07_curvaEpidemicaInizio.zip)

**Comment by aborruso** [comment]
Grazie mille

**Comment by aborruso** [comment]
Riapro, perché devo aggiungere il file del 7 dicembre
