### ISSUE TITLE
Cambiamento nel formato della comunicazione dei dati

### ISSUE THREAD

**Issue by mattodeg** [ondata/covid19italia#73]
Dando un'occhiata al Vostro lavoro (veramente interessante, non sono riuscito ad estrarre i dati dal sito del Governo sui vaccini) vorrei personalmente consigliare un formato di visualizzazione dei dati molto più intuitivo e comodo. Attualmente ad ogni riga, per esempio nel file delle Fasce d'età viene corrisposta una data, la cui colonna precedente riguarda il numero di vaccinazioni per la specifica fascia. Anzichè impostare il tutto riga per riga, sarebbe utile impostare per colonne, come di seguito:

|Regione|Aggiornamento|Fascia1619|Fascia2029|Fascia3039|Fascia4049|Fascia5059|Fascia6069|Fascia7079|Fascia8089|Fascia90|
|---|---|---|---|---|---|---|---|---|---|---|

Si avrebbe così una lettura molto più agevolata e si potrebbe vedere molto più chiaramente l'andamento per fascia d'erà.

Analoga considerazione per il sesso:
|Regione|Aggiornamento|Maschi|Femmine|
|---|---|---|---|

E per la categoria
|Regione|Aggiornamento|Operatori socio sanitari|Personale non sanitario|Ospiti strutture residenziali|
|---|---|---|---|---|

Mentre per le somminsitrazioni si potrebbe creare una tabella con
|Abruzzo_consegnate|Abruzzo_somministrate|Basilicata_consegnate|Basilicata_somministrate|...|Aggiornamento|
|---|---|---|---|---|---|

E via dicendo per ogni regione/provincia autonoma. In alternativa si potrebbe creare un csv per regione. La percentuale di somministrazione sul totale di dosi calcolate è un dato facilmente calcolabile da chi utilizza i dati.

Sperando di essermi chiarito, vi auguro buona serata.

**Comment by aborruso** [comment]
Ciao @MattoDeg grazie per i consigli.

Ci sono diversi modi per strutturare dati. Due suddivisioni di massima, molto note per chi lavora con i dati, sono la _wide_ e la _long_ (per approfondire interessante [questa pagina](https://tidyr.tidyverse.org/articles/tidy-data) e sopratutto la [pubblicazione](https://www.jstatsoft.org/article/view/v059i10) di riferimento).

Quella che proponi tu è la prima, quella usata per questi dati è essenzialmente la seconda.

La _long_ è preferita (anche da me) come formato di input, come formato da cui partire.

Buona giornata
