### ISSUE TITLE
È possibile inserire una versione latest del file?

### ISSUE THREAD

**Issue by sapomnia** [ondata/covid19italia#75]
Ciao! Intanto grazie. Ma grazie davvero.
Credete sia possibile fare una versione latest del file? Un po' come quella che quell'uomo saggio che è Andrea Borruso ha suggerito di fare alla Prociv per i dati sui contagi?
Grazie

**Comment by aborruso** [comment]
Ciao Ric,
ci dovrebbe essere già, ma forse non ho capito la domanda:
<https://github.com/ondata/covid19italia/tree/master/webservices/vaccini/processing>

Il latest però è riferito non al dato corrente sul sito del ministero, ma all'ultima volta che lo script creato processa i dati dal ministero. Al momento avviene circa 15 minuti dopo le 7, le 13, e 19.

Possiamo aumentare la frequenza

**Comment by sapomnia** [comment]
Ciao Andrea, sono esattamente i file di cui avevo bisogno! Ti voglio bene!
Sulla frequenza nessun problema. Grazie ancora!
