### ISSUE TITLE
[miglioramento] spostare colonna codice_regione

### ISSUE THREAD

**Issue by pigreco** [ondata/covid19italia#77]
La colonna `codice_regione` è presente nei file [somministrazione.csv](https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/processing/somministrazioni.csv) e [latest_aomministrazioni.csv](https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/processing/latest_somministrazioni.csv) ([`vaccini/processing/`](https://github.com/ondata/covid19italia/tree/master/webservices/vaccini/processing)).

Suggerirei di portarla al primo posto, prima della colonna `regione`.

**Comment by aborruso** [comment]
Caro @pigreco il fatto di metterla per prima, cosa ti migliorerebbe??

Grazie

**Comment by pigreco** [comment]
> ro @pigreco il fatto di metterla per prima, cosa ti migliorerebbe??

@aborruso, per me è solo un fatto estetico, niente di più

grazie

**Comment by aborruso** [comment]
@pigreco allora la chiudo, ma lascio whishlist.

Se il progetto durerà nel tempo (spero di no), l'avremo tra le cose da fare
