### ISSUE TITLE
[Improvement] Aumentare frequenza serale polling Report Vaccini o almeno forzare un refresh prima di mezzanotte

### ISSUE THREAD

**Issue by lucace81** [ondata/covid19italia#78]
Ho visto che gran parte degli aggiornamenti della pagina avviene dopo le 19, quindi sarebbe utile pianificare in cron anche qualche polling successivo alle 19, e uno poco prima della mezzanotte. Questo permetterebbe di individuare meglio il numero di vaccinazioni giornaliere, che altrimenti verrebbero contate nel giorno successivo.

Grazie!
Luca

**Comment by aborruso** [comment]
Ciao @lucace81 ne ho aggiunto uno intorno alle 21:15 e uno alle 23:15.
