### ISSUE TITLE
[Improvement] Catalogare i dati sui vaccinati su un file per giorno

### ISSUE THREAD

**Issue by MarcoBuster** [ondata/covid19italia#79]
Sto parlando dei file `categoria.csv`, `fasceEta.csv`, `anagrafica.csv` (ecc...) in questa [cartella](https://github.com/ondata/covid19italia/tree/master/webservices/vaccini/processing). 
A mio avviso sarebbe meglio creare anche un nuovo file a ogni update con i dati attuali, seguendo il modello della repo della protezione civile:
![immagine](https://user-images.githubusercontent.com/14850025/103490758-4d6e6d00-4e1e-11eb-891e-3c88f4cd3204.png)

Inoltre, nei file "principali" `categoria.csv`, `fasceEta.csv` (ecc...) terrei solo un campo data (non capisco perché ce ne siano due) e tenerlo per primo.

**Comment by aborruso** [comment]
Ciao @MarcoBuster ce ne sono due, perché voglio tenere traccia anche della forma in cui è raccolto in fase di scraping.

Per il momento li lascio aggregati senza suddividerli per giorno, ma me la segno come cosa su cui lavorare non appena possibile.

**Comment by MarcoBuster** [comment]
Va bene. Comunque grazie mille per quello che state facendo, davvero un bel lavoro, bravi.

**Comment by aborruso** [comment]
Per il momento chiudo, ma lascio label whishlist attiva.

Grazie a te
