### ISSUE TITLE
[webservices/vaccini] Merge dati regionali

### ISSUE THREAD

**Issue by slarosa** [ondata/covid19italia#80]
Sarebbe utile avere un unico CSV per i dati regionali. 
Grazie.

**Comment by dbaroncelli** [comment]
Se volete tenere i vari CSV, una cosa che suggerisco è che somministrazioni.csv contenga al massimo 1 dato giornaliero per regione. Al momento ce ne sono anche 5-6 ad orari diversi, che occupano spazio e non sono di grande utilità.
Se esiste un dato aggiornato per il giorno corrente, aggiungetelo, ma cancellate quello vecchio.
Altrimenti il file diventa inutilmente gigante.

**Comment by aborruso** [comment]
@slarosa fatto

Ho estratto per il momento campo data e aggiunto codice regionale ISTAT

| somministrazioni | regione | siglaCategoria | identificativo | categoria | codice_regione | data |
| --- | --- | --- | --- | --- | --- | --- |
| 0 | Campania | TML_CAT_OSS | 31/12/2020_PF/BT_CAM_150191_OSPEDALE S.M.DELLE GRAZIE_16-19 | 1 - Operatori Sanitari e Sociosanitari | 15 | 2020-12-31 |
| 0 | Veneto | TML_CAT_ALTRO | 01/01/2021_PF/BT_VEN_5050201_OSPEDALE CA' FONCELLO_80-89 | 2 - Personale non Sanitario | 05 | 2021-01-01 |
| 0 | Trentino-Alto Adige | TML_CAT_PERSONALE | 02/01/2021_PF/BT_PAT_020301_APSP Valle del Vanoi Canal S.Bovo_30-39 | 2 - Personale non Sanitario | 04 | 2021-01-02 |
| 1 | Toscana | TML_CAT_RSA_OSPITI | 02/01/2021_PF/BT_TOS_090624_COVID19 - Ospedale di Orbetello_40-49 | 3 - Ospiti Strutture Residenziali | 09 | 2021-01-02 |
| 0 | Lazio | TML_CAT_PERSONALE | 28/12/2020_PF/BT_LAZ_180111_Centro Vaccinale Ospedaliero "Pertini"_20-29 | 2 - Personale non Sanitario | 12 | 2020-12-28 |
