### ISSUE TITLE
Timestamp Vaccinazioni

### ISSUE THREAD

**Issue by dbaroncelli** [ondata/covid19italia#83]
Sarebbe molto utile avere un timestamp vaccinazioni,
sullo stile di Our World In Data:
https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data-last-updated-timestamp.txt

In questo modo sarebbe possibile fare il polling (per esempio ogni ora) solamente su un piccolo file,
per sapere se c'è stato un aggiornamento.

**Comment by aborruso** [comment]
Ciao, il file è qui <https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/vaccini-data-last-updated-timestamp.txt>

Il contenuto dello stesso è il valore di aggiornamento letto a monte al momento dello scraping.

Per avere info su date e orario dell'aggiornamento, c'è il comodo RSS:<br>
<https://github.com/ondata/covid19italia/commits/master/webservices/vaccini/vaccini-data-last-updated-timestamp.txt.atom>

Se per te è ok, chiudi per favore la issue.

P.S. hai visto l'altra issue sui dati giornalieri con l'ultimo valore? Se sì, per favore, un riscontro anche di due parole è gradito, ed è un po' il sale. Grazie

**Comment by dbaroncelli** [comment]
Grazie! questo timestamp stringa è utilissimo

si, ho visto i nuovi file "Top", ottimo lavoro!
