### ISSUE TITLE
[Vaccini] Punti somministrazione - Province

### ISSUE THREAD

**Issue by Feibio93** [ondata/covid19italia#85]
Salve a tutti, provando a fare lo scraping dei dati per ottenere microdati per ogni punto di somministrazione del Veneto, mi sono accorto che i punti di somministrazione richiedevano un inserimento manuale della provincia, ma per 5 luoghi mi è stato impossibile trovare la relativa provincia, in quanto il nome del luogo è troppo generale (come per esempio "ex ospedale"), quindi chiedo se sia possibile aggiungere anche l'identificativo per la provincia accanto all'identificativo regionale. Grazie mille per l'ottimo lavoro!

**Comment by aborruso** [comment]
Ciao @Feibio93 prima di risponderti, ho bisogno di capire che fonte usi. Parli di scraping, quindi non starai usando i dati di questo repo, né del repo ufficiale.

O stai usando questo file https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/processing/datiRegioni/05.csv ?

Grazie

**Comment by Feibio93** [comment]
Esatto, sto usando quel file

**Comment by aborruso** [comment]
Ciao @Feibio93 in quel file non trovo la stringa `ex ospedale`. Ma detto questo, provo ad aggiungere qualche elemento.

La colonna identificativo, se la splitti per `_`, sembra contenere data, tipo di vaccino, regione, identificativo del punto, nome del punto e classe di età.

Info sulla provincia non ce ne sono. Però potresti fare due cose:

- investigare sulla colonna `identificativo_re3`. Sembra un identificativo importante. In qualche file online si legge di un `Codice Centro Clinico`. Cerca ad esempio `5050201` [questo](https://github.com/ondata/covid19italia/files/5780910/Registro_Nazionale_Dei_Comitati_Etici_19.06.2020.xlsx);
- capire se è utile incrociare questi dati, con gli [ufficiali](https://github.com/italia/covid19-opendata-vaccini/blob/master/dati/punti-somministrazione-latest.csv) pubblicati da poco.



| identificativo | identificativo_re0 | identificativo_re1 | identificativo_re2 | identificativo_re3 | identificativo_re4 | identificativo_re5 |
| --- | --- | --- | --- | --- | --- | --- |
| 06/01/2021_PF/BT_VEN_50506_CAMPOSAMPIERO MEDICO COMPETENT_90+ | 06/01/2021 | PF/BT | VEN | 50506 | CAMPOSAMPIERO MEDICO COMPETENT | 90+ |
| 04/01/2021_PF/BT_VEN_50506_VIA TEMANZA ANTI INFLUENZALE_20-29 | 04/01/2021 | PF/BT | VEN | 50506 | VIA TEMANZA ANTI INFLUENZALE | 20-29 |
| 03/01/2021_PF/BT_VEN_050506_CAMPOSAMPIERO MEDICO COMPETENT_16-19 | 03/01/2021 | PF/BT | VEN | 050506 | CAMPOSAMPIERO MEDICO COMPETENT | 16-19 |
| 30/12/2020_PF/BT_VEN_50501_AGORDO - SERVIZIO IGIENE_90+ | 30/12/2020 | PF/BT | VEN | 50501 | AGORDO - SERVIZIO IGIENE | 90+ |
| 27/12/2020_PF/BT_VEN_50501_BELLUNO "DRIVE-IN"_50-59 | 27/12/2020 | PF/BT | VEN | 50501 | BELLUNO "DRIVE-IN" | 50-59 |

**Comment by opencovid-mr** [comment]
L'identificativo contenuto nella colonna `identificativo_re3` sembra più o meno corrispondere al `Codice identifictivo struttura` dell'elenco [Strutture di Ricovero Pubbliche - Ministero della Salute](http://www.salute.gov.it/imgs/C_17_pubblicazioni_1053_allegato.XLS)

**Comment by Feibio93** [comment]
Grazie davvero ad entrambi, sono riuscito a trovare tutte le strutture mancanti!

Lascio il lavoro, modificato per la regione Veneto dal lavoro iniziale per la Puglia di Mimmo Cucinella
https://docs.google.com/spreadsheets/d/e/2PACX-1vQORp1uXpLQqzBPh4i1ru0Ip33IOcS7JUPqyWbIM-A6YKkA3shLcaqlGTfAGwv4QF4OsWUs68jwyoB7/pubhtml

**Comment by aborruso** [comment]
Ciao @Feibio93 che uso ne state facendo? Dove ne darete notizia?

**Comment by Feibio93** [comment]
Per il momento il mio uso è personale, quando avrò perfezionato grafici e spiegazioni testuali lo pubblicherò principalmente su Facebook, nei gruppi della provincia di Belluno. Ovviamente avrò cura di citarvi e impostare la licenza CC-BY. Vedrò se riesco a far pubblicare un articolo di giornale a riguardo

**Comment by aborruso** [comment]
Ciao @Feibio93 in giornata cambierò lo schema dati, estraendo le colonne con data, regione, classe di età e vaccino

**Comment by aborruso** [comment]
In ogni caso, stasera spegneremo la raccolta di questi dati: le richieste alle API superano il numero consentito e  vengono quindi restituiti dati parziali

**Comment by Feibio93** [comment]
Che peccato... sono dati molto interessanti e utili.

**Comment by aborruso** [comment]
@Feibio93 abbiamo fatto una modifica e ci facciamo restituire i dati soltanto quando sono state fatte più di zero somministrazioni.

Così, continueremo ancora, sino a nuovi limiti

**Comment by Feibio93** [comment]
Grandissimi... complimenti davvero per tutto questo lavoro
