### ISSUE TITLE
codici NUTS2 differenti per stesse regioni

### ISSUE THREAD

**Issue by pigreco** [ondata/covid19italia#89]
in questo file [1] ci sono codici NUTS2 differenti rispetto a questo altro file [2],

esempio Umbria `ITI2` e `ITE2`

[1] https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/risorse/popolazioneRegioni.csv#L6
[2] https://github.com/ondata/nuts/blob/main/processing/codiciNUTS.csv#L330

**Comment by aborruso** [comment]
@pigreco chiudo la issue.

I codici [del repo sui NUTS](https://github.com/ondata/nuts/blob/main/processing/codiciNUTS.csv#L330), sono corretti, vengono da [EUROSTAT](https://ec.europa.eu/eurostat/documents/345175/7451602/2021-NUTS-2-map-IT.pdf).

Ma anche i codici di questo repo dovrebbero essere corretti perché da API ISTAT (cerca l'Umbria):

```
curl "http://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_ITTER107" >./output.xl
```

Scriverò ad ISTAT per capire

**Comment by aborruso** [comment]
@pigreco ho preparato in attesa un file con tutte le codifiche https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/risorse/codiciTerritoriali.csv

**Comment by pigreco** [comment]
@aborruso ,

condivido un gist con tutti i casi da me conosciuti:

https://gist.github.com/pigreco/d7f7cb6d11add225f10781374c68bada

**Comment by aborruso** [comment]
> esempio Umbria `ITI2` e `ITE2`

Sembra che le API di ISTAT espongano i valori NUTS nella codifica del 2006.
