### ISSUE TITLE
tabula.technology

### ISSUE THREAD

**Issue by pitmonticone** [ondata/covid19italia#9]
Accidenti non ero a conoscenza di questa mancanza. 

Consiglio l'utilizzo di [tabula](https://tabula.technology) per velocizzare il processo di conversione (ammesso che non ne stiate già usando uno simile o migliore).

Grazie mille per il vostro preziosissimo lavoro. 

Allegati: 

1. PDF [5-marzo.pdf](https://github.com/ondata/covid19italia/files/4295748/5-marzo.pdf)
2. csv <img width="1239" alt="Screenshot 2020-03-06 at 00 34 31" src="https://user-images.githubusercontent.com/38562595/76036645-f9b49e00-5f44-11ea-8f58-4a244c5993af.png">

TW: [@PietroMonticone](https://twitter.com/PietroMonticone)

**Comment by aborruso** [comment]
Ciao, non lo facciamo a mano, sarebbe da matti :)
Specie per l'altra tabella, quelle delle province.

Trovi il codice nella radice del repo
