### ISSUE TITLE
Corretta decodifica dati JSON dal servizio PowerBI

### ISSUE THREAD

**Issue by svavassori** [ondata/covid19italia#91]
**Se la tua richiesta è relativa ad un problema descrivicela per favore.**

Ho cercato in varie parti, ma sembra che non ci sia nessuna documentazione sul linguaggio di query e sul formato del risultato in JSON per decodificare correttamente la risposta del server.

**Descrivi la soluzione che ti piacerebbe**

Dopo vari giorni in cui ho provato a dare un senso credo (spero) di aver capito come decodificare correttamente i campi "R" e "Ø" che vengono con l'array "C".
Visto che stavo facendo lo stesso lavoro che voi (capire come estrarre i dati dal server PowerBI) mi sembra più logico ed efficiente unire quello che ho trovato rispetto a duplicare il lavoro

In sostanza, per le prove che ho fatto sembra che il campo "R" è un bitset che contiene gli indici che si devono copiare dall'array "C" precedente mentre il campo "Ø" è un bitset che indica gli indici che devono essere vuoti e i rimanenti indici/elementi sono quelli presenti nel campo "C" corrente.

Credo che sia una forma per risparmiare spazio facendo un differenziale tra il "C" attuale ed il "C" precedente.

Ho creato uno script in Python prendendo spunto da [questo](https://gist.github.com/kalloc/4486fa6640658add867bcbb7d551ff35#file-powerbi_extractor-py) (ho appena iniziato con Python, quindi non spaventatevi se vedete degli orrori).
Lo script è un grado di convertire il risultato dei punti di somministrazione di tutte le regioni (una query invece di 20)

**Descrivi le alternative considerate**
Aspettare che pubblichino i dati in un formato decente

**Altro materiale**

Gist del file: https://gist.github.com/svavassori/3319ff9d7e16a8788665ca59a5a04889

**Comment by aborruso** [comment]
Ciao @svavassori ottimo, grazie.

Non posso mettermi a testarlo/usarlo da subito. Se ne crei una versione che posso lanciare in cron in ambiente python 3, creo una github action dedicata e lo aggiungo alla pipeline.

Facciamo 20 query in alcuni casi, perché le API hanno un limite 30000 record di output e abbiamo messo le mani avanti. In questo caso non servirà, perché non si supereranno.

**Comment by svavassori** [comment]
Ho riscritto e pulito lo script (ver 2), la sintassi è:

`python3 powerbi_extractor.py <input-file.json> <output-file.csv>`

l'output è un CSV, nel caso fosse più comodo un JSON, posso cambiarlo.

**Comment by aborruso** [comment]
grazie @svavassori.

Mi metti da qualche parte il JSON con la query per per i punti di somministrazione?

**Comment by svavassori** [comment]
Eccola: https://gist.github.com/svavassori/ad90384cae8aac11c5da165a1b839f3a

Non so se ti occorrono altri campi o se sono nell'ordine corretto

**Comment by aborruso** [comment]
Se lancio

```
python3 ./query_punti-di-somministrazione.json ./powerbi_extractor.py
```

non ho nulla in output. Cosa sbaglio?

**Comment by aborruso** [comment]
Sbaglio a leggere, scusami

**Comment by svavassori** [comment]
Normalmente lancio le query con così:

`curl -s 'https://wabi-europe-north-b-api.analysis.windows.net/public/reports/querydata?synchronous=true' --compressed -H 'Content-Type: application/json;charset=UTF-8' -H 'X-PowerBI-ResourceKey: 388bb944-d39d-4e22-817c-90d1c8152a84' --data @query_punti-di-somministrazione.json | jq`

**Comment by aborruso** [comment]
@svavassori se lo lancio con

```
python3 powerbi_extractor.py query_punti-di-somministrazione.json output.csv
```

ho

```
Traceback (most recent call last):
  File "/mnt/c/Users/aborr/Desktop/trash/testp/powerbi_extractor.py", line 76, in <module>
    main()
  File "/mnt/c/Users/aborr/Desktop/trash/testp/powerbi_extractor.py", line 71, in main
    extract(sys.argv[1], sys.argv[2])
  File "/mnt/c/Users/aborr/Desktop/trash/testp/powerbi_extractor.py", line 9, in extract
    data = input_json["results"][0]["result"]["data"]
KeyError: 'results'
```

**Comment by svavassori** [comment]
query_punti-di-somministrazione.json contiene la query, non il risultato

**Comment by aborruso** [comment]
> query_punti-di-somministrazione.json contiene la query, non il risultato

@svavassori questo lo immaginvavo. E avevo capito quindi di lanciarlo con

```
python3 script.py query.json output.csv
```

Non va lanciato così?

**Comment by svavassori** [comment]
`curl -s 'https://wabi-europe-north-b-api.analysis.windows.net/public/reports/querydata?synchronous=true' --compressed -H 'Content-Type: application/json;charset=UTF-8' -H 'X-PowerBI-ResourceKey: 388bb944-d39d-4e22-817c-90d1c8152a84' --data @query_punti-di-somministrazione.json | jq > query_result.json
`

`python3 powerbi_extractor.py  query_result.json  query_result.csv`

**Comment by aborruso** [comment]
Perfetto, scusami ma è giornata difficile.

It works !!!

Tra un po' metto in pipeline, entro cena. Ti vorrei citare. Mi puoi dare nome e cognome e (se ti va) un URL (un tuo sito, un tuo profilo social, ....)


Grazie

**Comment by svavassori** [comment]
Non ti preoccupare: solo quando mi hai scritto il comando ho capito che pensavi che lo script lanciasse la query invece di convertire il risultato.

Sergio Vavassori, e come URL se vuoi puoi mette il mio utente GitHub

**Comment by aborruso** [comment]
Sergio, grazie:

- inserito nota nel [README](https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/README.md);
- creato [script](https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/puntiSomministrazione.sh) che pilota il tuo script;
- inserito [file CSV nel repo](https://github.com/ondata/covid19italia/blob/master/webservices/vaccini/processing/puntiSomministrazione/puntiSomministrazione.csv#L13), con una prima aggiunta di codici geografici regionali (vorrei con calma inserire i codici comunali;
- attivato [aggiornamento giornaliero quotidiano](https://github.com/ondata/covid19italia/blob/master/.github/workflows/vacciniPuntiSomministrazione.yml)
