### ISSUE TITLE
Uniformare descrizione del vaccino

### ISSUE THREAD

**Issue by PBra** [ondata/covid19italia#94]
nei dati odierni il nome del vaccino somministrato viene riportato con diverse diciture:

COVID-19   VACCINE MODERNA*10FL
Moderna

COMIRNATY   Vaccino a mRNA contro COVID-19
PF/BT

Forse andrebbe uniformato il nome

**Comment by aborruso** [comment]
Ciao @PBra , non conosciamo come a monte i dati siano inseriti, e quindi non abbiamo criteri di controllo per intercettare queste difformità.

Potremmo costruire una regola su questi casi, ma domani ne potrebbero venirne di nuovi. Per questa ragione al momento lasciamo i dati grezzi.

Chiudo la issue, la associo all'etichetta `whishlist` e se nel tempo emergerà una lista di "correzioni" stabili, verrà implementata.

Grazie
