### ISSUE TITLE
Dati Agenas

### ISSUE THREAD

**Issue by Paulsword** [ondata/covid19italia#99]
Ciao,
vedo che i dati Agenas sono in ritardo - cosa mai accaduta. Saranno comunque aggiornati o è uno stop definitivo?
Grazie

**Comment by aborruso** [comment]
Buonasera @Paulsword purtroppo ieri si è verificato un problema.
I dati del 24 non sono stati archiviati. Mi spiace.

Quelli del 25, sono stati aggiornati.

Per curiosità: per cosa li usi? C'è qualcosa di pubblico da guardare?
Te lo chiedo soltanto per il piacere.

Saluti

**Comment by Paulsword** [comment]
Grazie molte.
Li uso per integrare le informazioni dei carichi sanitari in queste slide, pubblicate dalla pagina Facebook di Pillole di Ottimismo.
https://public.flourish.studio/story/722265/

**Comment by aborruso** [comment]
@Paulsword grazie a te. Raccogliere questi dati e spingere su questa si fa anche per produrre delle conseguenze, come il tuo bel lavoro.

Sbaglio o nella/e slide in cui siti i dati da questa fonte, non ci sono informazione sulla fonte?

Puoi per cortesia inserirla come onData, con link a <https://github.com/ondata/covid19italia/tree/master/webservices/agenas>?

Grazie a te

**Comment by Paulsword** [comment]
Lo farò. Cito Agenas come origine dei dati, ma mi pare corretto mettere anche la fonte intermedia.
Citavo già OnData nella slide sulle vaccinazioni, prima del repository ufficiale.
Grazie ancora
